config/routes.rb
Rails.application.routes.draw do
  get 'welcome/home'
  get 'welcome/about'
  get 'welcome/press'
  get 'welcome/hair_loss'
  get 'store/hello'
  post "welcome/form_route" => "welcome#form_route", :as => :form_route

  get 'sitemap' => 'welcome#sitemap'
  root 'welcome#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def hello
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  respond_to :html, :xml
  def home
  end

  def about
  end
  
  def press
  end	

  def sitemap
  end	

  def hair_loss
  end	

  def form_route
    @params = params
    # respond_to do |format|
      # Thread.new do 
        # JforuMailer.inquiry_confirmation(@params).deliver
        # p "&" * 100
        JforuMailer.send_to_admin(@params).deliver
      # end
    # end
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="google-site-verification" content="UBHzatp3ZvhLQQ0PDpQ9R7IdeILJeaZ4Ce-mfBpFkoI" />

    <title><%= content_for?(:title) ? yield(:title) : "The Perfect Fit" %></title>
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <%= favicon_link_tag 'favco_jforu2.ico' %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
<body>


  <header class="row ">
    <section class="columns small-12 medium-6 large-5">
      <h1 class="">The Perfect Fit, Just for You LLC</h1>
      <div class="row">
        <div class="columns small-12 medium-7 right">
          <span id="store-hours">Tues - Sat. 11:00 - 6:00PM EST  <a href="tel:+1-845-389-7950"><h3 class="store-hours">(845) 594-5055</h3></a></span>
        </div>
      </div>
    </section>
    <!--  <section class=" phone columns small-12 medium-5 large-4 left">
        <img src="http://shop.bgs.ac.uk/images/present.png" alt="" style="display:inline-block; height:155px; float:left">
        <h1 class="h1-add" style="font-size:2em"><span style="font-size:20px; color:black; display:block;">Checkout our</span> Christmas Sales</h1>
        <h4>Deals Deals Deals!</h4>
      </section> -->

  </header>

  <%= render 'shared/navigation' %>

  <%= yield %>

  <footer class="row">
    <article class="columns small-12 medium-4 large-3">
      <ul>
        <li> <i class="fa fa-clock-o fa-2x"></i> &nbsp;Hours of Operation</li>
        <li>Tuesday - Saturday: 11am- 6pm</li>
        <li>Sunday: Closed</li>
        <li>Monday: By Appointment Only</li>
      </ul>
      <ul>
        <li><i class="fa fa-envelope-o fa-2x"></i>&nbsp;Address</li>
        <li>516 Broadway 2nd Floor Ste 6</li>
        <li>Kingston, New York 12401</li>
        <li>P: (845) 594-5054</li>
        <li>P: (845) 594-5055</li>
      </ul>
    </article>
    <article class="social columns small-12 medium-3 large-6 ">
      <%= image_tag("theperfectfitlogo.png") %>
    </article>

    <article class=" columns small-12 medium-3 large-2 left icons">
      <a href="https://www.facebook.com/pages/The-Perfect-Fit-Just-for-You/604031709684433"><i class="fa fa-facebook-square fa-5x"></a></i> &nbsp;

      <i class="fa fa-twitter-square fa-5x"></i> &nbsp;
    </article>
  </footer>
   <%= javascript_include_tag "application" %>
      <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-55424459-1', 'auto');
        ga('send', 'pageview');

       </script>
</body>

</html>

app/views/shared/_inquiry_form.html.erb
<div class="columns small-12 medium-4 form-style">

<%= form_tag('welcome/form_route', remote: true, class: 'form') do %>
<h3 class="h-3">Contact Us</h3>
  <%= text_field_tag 'name',nil, placeholder: '  jon doe', required: 'true' %>
  <%= email_field_tag 'email',nil, placeholder: '  me@gmail.com', required: 'true'%>
  <%= text_field_tag 'subject',nil, placeholder: '  Subject', required: 'true'%>
  <%= text_area_tag 'body', nil, rows: 10, cols: 25,placeholder: '  Message', required: 'true' %>
  <%= submit_tag("Send") %>
<% end %>
</div>

app/views/shared/_navigation.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/welcome/home">The Perfect Fit</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
 <!--    <ul class="right">
      <li class="active"><a href="#">Right Button Active</a></li>
      <li class="has-dropdown">
        <a href="#">Right Button Dropdown</a>
        <ul class="dropdown">
          <li><a href="#">First link in dropdown</a></li>
          <li class="active"><a href="#">Active link in dropdown</a></li>
        </ul>
      </li>
    </ul> -->

    <!-- Left Nav Section -->
    <ul class="left">
      <li><a href="/welcome/hair_loss">Custom Wigs</a></li>
      <li><a href="/welcome/home#education">Education</a></li>
      <li><a href="/welcome/about">About Us</a></li>
      <!-- <li><a href="/welcome/press">Press</a></li>   -->
    </ul>
  </section>
</nav>

app/views/store/hello.html.erb
<h1>Store#hello</h1>
<p>Find me in app/views/store/hello.html.erb</p>

app/views/welcome/about.html.erb
<!-- <section class="filler">
</section> -->

<section class=" content row">
	<aside class=" columns small-12 medium-4 circular">
		<div>
        <%= image_tag("Tammara_wigs-3126-Edit.jpg") %>
		
    </div>
		
	</aside>
	<article class="  columns small-12 medium-8">
		<h1>About the Founder</h1><h3>CEO Tammara Taylor</h3>
		<p>Mrs.Taylor was inspired by her mother and sister after cancer took their lives too soon. On February 11, 2011, Mrs. Taylor was in a devastating car crash that nearly ended her life. These experiences led her to realize the fragility of life, and to promise that her life would not be wasted. She soon learned to make wigs for herself while recovering in a wheelchair, and was thrilled by her new hobby. After a routine mammogram at Benedictine Hospital, God gave Mrs.Taylor the idea to volunteer her service by making ten wigs for cancer patients. The first patient changed Mrs. Taylor's outlook on wigs and made her realize their ability to promote confidence and positivity. She now realized that she could be part of the healing process for chemotherapy patients. Mrs.Taylor subsequently attended school to learn to make custom wigs by machine and by hand. The Perfect Fit will soon open an office and unique beauty and health supply store at 516 Broadway in Kingston, New York. Due to our belief that beauty begins on the inside, all of our locations will include organic beauty products and supplements at the affordable prices. At The Perfect Fit, we hope to see you grow with us one strand at a time.
		</p>
	</article>
</section>

<section class=" content row">
	<aside class="columns small-12 medium-4 circular">
		<div>
		<!-- <img src="/assets/jforu.jpg" alt="Tammara"> -->
		<%= image_tag("jforu.jpg") %>
    </div>
		
	</aside>
	<article class="columns small-12 medium-8">
		<h1>The Company - Just For You</h1>
		<p>The Perfect Fit aims to help women, men, and children regain confidence after suffering from illness-related hair loss. We also enjoy serving members of the general public who want to make a fashion statement. The company was founded by Tammara L. Taylor, a specialist in custom wigs and an expert in her field.
		</p>
	</article>
</section>

app/views/welcome/hair-loss.html.erb
<section class=" content row">
	
	<article class="columns small-12">
		<h2>Hair-loss</h2>
	  <p>Do you suffer with hair loss? Whether it’s natural hair loss, genetic hair loss or hair loss from cancer treatments, there is something you can do about your hair loss. Anyone can experience hair loss. Women actually make up a large percentage of American hair loss sufferers <strong>(1 in 4 women suffer from hair loss in the U. S. alone)</strong>, that’s over <strong>40 million women</strong>. </p>

	
	<ul>
		 
		<h3>Common Causes of Hair Loss</h3>
		<li>Heredity/Genetics</li>
		<li>Chemotherapy</li>
		<li>Radiation</li>
		<li>Stress/Trauma</li>
		<li>Illness/Disease</li>
		<li>Medications</li>
		<li>Age</li>
		<li>Poor Nutrition</li>
		<li>Hormonal Changes </li>
	</ul>
		<p>
		Alopecia is the medical term for excessive hair loss. It can be caused by various factors. 
		Whatever the reason may be for you, we have <strong class="color">“The Perfect Fit Just For You.”</strong>  What makes us different?  We are capable of customizing a unit that will be constructed just for you. We can construct a wig using your own hair, or we can use the top of the line highest grade of human hair for the most natural look. </p>
		<p>
		We are committed to creating gorgeous hair. Our priority is to help our clients look and feel their best! We go the extra mile for our clients. Schedule a one on one with one of our wig specialist and find out more information. We look forward to hearing from you. 
		 </p>
	</article>
</section>

app/views/welcome/hair_loss.html.erb
<section class=" row hair_loss">
	<article class="columns small-10 large-centered">
		<h2>Hair-loss</h2>
	  <p>Do you suffer with hair loss? Whether it’s natural hair loss, genetic hair loss or hair loss from cancer treatments, there is something you can do about your hair loss. Anyone can experience hair loss. Women actually make up a large percentage of American hair loss sufferers <strong>(1 in 4 women suffer from hair loss in the U. S. alone)</strong>, that’s over <strong>40 million women</strong>. </p>
	<ul>
		 
		<h3>Common Causes of Hair Loss</h3>
		<li>Heredity/Genetics</li>
		<li>Chemotherapy</li>
		<li>Radiation</li>
		<li>Stress/Trauma</li>
		<li>Illness/Disease</li>
		<li>Medications</li>
		<li>Age</li>
		<li>Poor Nutrition</li>
		<li>Hormonal Changes </li>
	</ul>
		<p>
		Alopecia is the medical term for excessive hair loss. It can be caused by various factors. 
		Whatever the reason may be for you, we have <strong class="color">“The Perfect Fit Just For You.”</strong>  What makes us different?  We are capable of customizing a unit that will be constructed just for you. We can construct a wig using your own hair, or we can use the top of the line highest grade of human hair for the most natural look. </p>
		<p>
		We are committed to creating gorgeous hair. Our priority is to help our clients look and feel their best! We go the extra mile for our clients. Schedule a one on one with one of our wig specialist and find out more information. We look forward to hearing from you. 
		 </p>
	</article>
</section>

app/views/welcome/home.html.erb
<!-- <section class="intro-images row">
		<%=	image_tag("banner_foru_brands.jpg")%>
</section> -->

<section class="featured-wig row" id="featured-wigs">
	<h3>Just for You store coming soon!</h3>
	<article class=" feature columns small-12 medium-6 large-3">
		<div class="image-wrapper">

			<div class="featured-titles columns small-12"> <h2>WIGS TO LOVE</h2></div>
			<div class="featured-img">

			<%=	image_tag("ORCHID WIG BY ESTETICA DESIGNS.png")%>
			</div>
			<div class="featured-stars"><i class="fa fa-star fa-2x"></i> &nbsp;<i class="fa fa-star fa-2x"></i> &nbsp;<i class="fa fa-star fa-2x"></i> &nbsp;<i class="fa fa-star fa-2x"></i> &nbsp;</div>
		</div>
	</article>
	<article class=" feature columns small-12 medium-6 large-3">
		<div class="image-wrapper">

			<div class="featured-titles columns small-12"> <h2>Lace Fronts</h2></div>
			<div class="featured-img">
				<%=image_tag("Jill (Futura) SSW IFW.png")%>
			</div>
			<div class="featured-stars"><i class="fa fa-star fa-2x"></i> &nbsp;<i class="fa fa-star fa-2x"></i> &nbsp;<i class="fa fa-star fa-2x"></i> &nbsp;<i class="fa fa-star fa-2x"></i> &nbsp;</div>
	  </div>
	</article>
	<article class=" feature columns small-12 medium-6 large-3">
		<div class="image-wrapper">

			<div class="featured-titles columns small-12"> <h2>Short & Sexy</h2></div>
			<div class="featured-img">
			<%=	image_tag("SHEER TOUCH MODERATE HAIRPIECE copy.png") %>
			</div>
			<div class="featured-stars"><i class="fa fa-star fa-2x"></i> &nbsp;<i class="fa fa-star fa-2x"></i> &nbsp;<i class="fa fa-star fa-2x"></i> &nbsp;<i class="fa fa-star fa-2x"></i> &nbsp;</div>
		</div>
	</article>
	<article class=" feature columns small-12 medium-6 large-3">
		<div class="image-wrapper">
			<div class="featured-titles columns small-12"> <h2>Featured Brands</h2></div>
			<div class="featured-img">
				<%=	image_tag("Lisa (Futura) SSW IFW.png") %>
			</div>
			<div class="featured-stars"><i class="fa fa-star fa-2x"></i> &nbsp;<i class="fa fa-star fa-2x"></i> &nbsp;<i class="fa fa-star fa-2x"></i> &nbsp;<i class="fa fa-star fa-2x"></i> &nbsp;</div>
	  </div>
	</article>
</section>
<section class=" row transparent-white" id="hair-loss">

	<article class="columns small-12 medium-6">
		<h2>Hair-loss</h2>
	  <p>Do you suffer with hair loss? Whether it’s natural hair loss, genetic hair loss or hair loss from cancer treatments, there is something you can do about your hair loss. Anyone can experience hair loss. Women actually make up a large percentage of American hair loss sufferers <strong>(1 in 4 women suffer from hair loss in the U. S. alone)</strong>, that’s over <strong>40 million women</strong>. </p>

	<%= link_to "read more", welcome_hair_loss_path, class: "color" %>
	</article>

	<article class=" columns small-12 medium-6">
		<h2>Custom Wigs</h2>
		<p>Custom wigs is what we do best here at The Perfect Fit. We are able to bring any style to life and make it fit you personally. We sit down with you and have a Heart to Hair Talk about what would be best suited for you. There are a number of ways that we go about doing this: 1. We may view old photographs, 2.We may go thru some of our customized wig collections 3. We will discuss various options with you about what fits you and your lifestyle. Whatever the case, our goal is to make <strong>YOU </strong>happy. Our company works with people to help people. </p>
	</article>
</section>
<section class="row education" id="education">
	<article class=" columns small-12 medium-6">
		<h2> <i class="fa fa-book "></i> &nbsp;Education / Workshops</h2>
		<p>The Perfect Fit, Just For You LLC is proud to have it’s first ever Educational Workshop coming in October 2014, Tammara Taylor will be conducting a special class: <strong class="color">“The Art of Wig Making.” </strong> The goal of this class is to teach an individual how to make their own custom wig, and to allow them the freedom to create through the art of customization. This is something that they can go further with through taking other classes to truly hone in on the wig making profession and possibly become entrepreneurs or work for The Perfect Fit on a Part-time basis. This is a skill that can be taken further. Please give us a call for more details on this Workshop. (845) 594-5055.
    </p>
	</article>

	<article class=" columns small-12 medium-6">
		<h2><i class="fa fa-calendar "></i> &nbsp;Upcoming Events</h2>
		<p>In 2015 The Perfect Fit, Just For You will be hosting our second Fashion Show. It will be filled with many exciting activities, music and fun entertainment. Our goal is to raise awareness for people that are fighting all forms of Cancer. If you would like to be a part of making this wonderful event happen please give us a call at (845) 594-5055.
    </p>
	</article>

</section>
<section class=" row" id="amazon-products">
	<h3>Products we love!</h3>

	<div class="columns small-12 medium-4">
		<iframe src="http://rcm-na.amazon-adsystem.com/e/cm?t=thpefi-20&o=1&p=12&l=ur1&category=beauty_editorspicks&banner=1A5SHYGPKCSPBAZ2PF02&f=ifr&lc=pf4&linkID=GPPXSYKDXY44NR4U" width="300" height="250" scrolling="no" border="0" marginwidth="0" style="border:none;" frameborder="0"></iframe>
	</div>
	<div class="columns small-6 medium-2">
		<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=thpefi-20&marketplace=amazon&region=US&placement=B00F5BNWL8&asins=B00F5BNWL8&linkId=G2JWAJBLGQP7RDXZ&show_border=true&link_opens_in_new_window=true">
		</iframe>
	</div>

	<div class="columns small-6 medium-2">
		<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=thpefi-20&marketplace=amazon&region=US&placement=B00EN22ZRC&asins=B00EN22ZRC&linkId=LNXM5BRUPSR4IJYX&show_border=true&link_opens_in_new_window=true">
		</iframe>
	</div>
	<div class="columns small-6 medium-2">
			<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=thpefi-20&marketplace=amazon&region=US&placement=0240813200&asins=0240813200&linkId=CRUK2IXDYTO345H4&show_border=true&link_opens_in_new_window=true">
		  </iframe>
	</div>

	<div class="columns small-6 medium-2">
		<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=thpefi-20&marketplace=amazon&region=US&placement=B003KPEHGU&asins=B003KPEHGU&linkId=E4OVMSL6MVSXBZ66&show_border=true&link_opens_in_new_window=true">
		</iframe>
	</div>
</section>

<!-- <div class="columns small-6 medium-2">
	<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=thpefi-20&marketplace=amazon&region=US&placement=B008U5JB3Y&asins=B008U5JB3Y&linkId=NOOWWTADTPIS6PKT&show_border=true&link_opens_in_new_window=true">
	</iframe>
</div>
 -->

<!-- <section class=" row float-right" id="testimonials">
	<%= render 'shared/inquiry_form' %>
</section> -->

app/views/welcome/press.html.erb
<h1>presspage</h1>